# Generated by Django 4.0.3 on 2022-05-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='fld_email', max_length=100, unique=True, verbose_name='Email')),
                ('mobile', models.CharField(db_column='fld_mobile', max_length=100, unique=True)),
                ('password', models.CharField(db_column='fld_password', max_length=255)),
                ('first_name', models.CharField(blank=True, db_column='fld_first_name', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='fld_last_name', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='fld_address', max_length=255, null=True)),
                ('check_in_time', models.TimeField(blank=True, db_column='fld_check_in_time', null=True)),
                ('check_out_time', models.TimeField(blank=True, db_column='fld_check_out_time', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='fld_last_login_datetime', null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(blank=True, db_column='fld_is_delete', null=True)),
                ('created_datetime', models.DateTimeField(blank=True, db_column='fld_created_datetime', null=True)),
                ('datetime_timestamp', models.DateTimeField(blank=True, db_column='fld_datetime_timestamp', null=True)),
                ('is_admin', models.BooleanField(db_column='fld_is_admin', default=False)),
                ('user_level', models.ForeignKey(blank=True, db_column='fld_user_level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.tbluserlevel')),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
