# Generated by Django 4.0.3 on 2022-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(db_column='fld_is_delete', default=False),
        ),
    ]
