# Generated by Django 4.0.3 on 2022-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUserLevel',
            fields=[
                ('fld_ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('fld_user_level_name', models.CharField(blank=True, max_length=20, null=True)),
                ('fld_is_active', models.BooleanField(default=True)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_user_level',
                'managed': True,
            },
        ),
    ]
