# Generated by Django 4.0.3 on 2022-05-22 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audittrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('script', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('table', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('keyvalue', models.TextField(blank=True, null=True)),
                ('oldvalue', models.TextField(blank=True, null=True)),
                ('newvalue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audittrail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint', models.TextField()),
                ('publickey', models.CharField(max_length=255)),
                ('authenticationtoken', models.CharField(max_length=255)),
                ('contentencoding', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdmin',
            fields=[
                ('fld_ai_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fld_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_username', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_password', models.CharField(blank=True, max_length=255, null=True)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRates',
            fields=[
                ('fld_ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('fld_state', models.IntegerField(blank=True, null=True)),
                ('fld_rate', models.IntegerField(default=True)),
                ('fld_is_active', models.BooleanField(default=True)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_rates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSites',
            fields=[
                ('fld_ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('fld_site_type', models.CharField(blank=True, max_length=6, null=True)),
                ('fld_site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_state', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_district', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_is_active', models.BooleanField(default=True)),
                ('fld_is_delete', models.BooleanField(default=False)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_sites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserSites',
            fields=[
                ('fld_ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('fld_assigned_date', models.DateTimeField(blank=True, null=True)),
                ('fld_is_active', models.BooleanField(default=True)),
                ('fld_is_delete', models.BooleanField(default=False)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('fld_sites', models.ManyToManyField(blank=True, null=True, to='database.tblsites')),
                ('fld_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_sites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserDevices',
            fields=[
                ('fld_ai_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fld_device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_imei', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_is_active', models.BooleanField(default=True)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('fld_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblAttendance',
            fields=[
                ('fld_ai_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fld_attendance_status', models.CharField(blank=True, max_length=9, null=True)),
                ('fld_latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_device_info', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('fld_is_active', models.BooleanField(default=True)),
                ('fld_is_delete', models.BooleanField(default=False)),
                ('fld_date', models.DateField(blank=True, null=True)),
                ('fld_time', models.TimeField(blank=True, null=True)),
                ('fld_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('fld_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_attendance',
                'managed': True,
            },
        ),
    ]
