# Generated by Django 4.0.3 on 2022-05-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_audittrail_subscriptions_tbladmin_tblrates_tblsites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblusersites',
            name='fld_sites',
            field=models.ManyToManyField(to='database.tblsites'),
        ),
    ]
