# Generated by Django 4.0.3 on 2022-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_tblusersites_fld_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblattendance',
            name='fld_attendance_status',
            field=models.CharField(blank=True, choices=[('ci', 'check_in'), ('cr', 'current'), ('co', 'check_out')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tblattendance',
            name='fld_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblrates',
            name='fld_state',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblsites',
            name='fld_state',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
