# Generated by Django 4.0.3 on 2022-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_tblattendance_fld_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrates',
            name='fld_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
